# Site settings
title: Founders & Coders
email: contact@founderandcoders.org
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://foundersandcoders.org" # the base hostname & protocol for your site
twitter_username: fonderscoders
github_username:  foundersandcoders
markdown: kramdown
host: 0.0.0.0
exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]

gems:   
  - jekyll-redirect-from
sass:
  style: compressed
